apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oci-push-smoke.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oci-push-smoke.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  message: {{ .Values.message | quote }}
