apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oci-push-smoke.fullname" . }}
  labels:
    {{- include "oci-push-smoke.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oci-push-smoke.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oci-push-smoke.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: oci-push-smoke
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "oci-push-smoke.fullname" . }}
                  key: message
            - name: PORT
              value: "8080"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
